### ISSUE TITLE
provider not found with authorize route

### ISSUE THREAD

**Issue by mookie5dc** [salsify/omniauth-multi-provider-saml#4]
I'm using this gem with Devise.  I've setup the routes as such:

```
devise_scope :user do
    match 'users/auth/saml/:identity_provider_id/callback',
        via: [:get, :post],
        to: 'users/omniauth_callbacks#saml'
    match 'users/auth/saml/:identity_provider_id',
        via: [:get, :post],
        to: 'users/omniauth_callbacks#passthru'
end
```

When I run rake routes, it seems like it's mapped properly:

```
GET|POST       /users/auth/saml/:identity_provider_id/callback(.:format)    users/omniauth_callbacks#saml
GET|POST       /users/auth/saml/:identity_provider_id(.:format)    users/omniauth_callbacks#passthru
```

But when I hit the route: http://localhost:3000/users/auth/saml/someid
it returns the following:
Not found. Authentication passthru.

I see that the regular provider routes also use the action passthru, but when I add  debug statement there(in my omniauth_callbacks_controller), it doesn't hit that line.  Any ideas on where the routing is evaluated for this provider?

**Comment by jturkel** [comment]
@mookie5dc - What does your omniauth initializer look like?

**Comment by mookie5dc** [comment]
I finally figured it out.  I the request_path? was returning false because I did not pass the path_prefix into the handler.  (I assumed Omniauth.config.path_prefix was set).  My setup is slightly different because I'm using it with Devise, so I don't use the register call:

```
 # setup for multiprovider SAML options                  
  dynamic_options_generator = lambda { |identity_provider_id, rack_env|
    identity_provider = IdentityProvider.find_by!(uuid: identity_provider_id )
    identity_provider.options
  }

  path_prefix =  '/users/auth'
  identity_provider_id_regex =  /[\w|\.]+/
  handler = OmniAuth::SAML::MultiProvider::Handler.new(path_prefix: path_prefix,
                                                       identity_provider_id_regex: identity_provider_id_regex,
                                                       &dynamic_options_generator)
  saml_options = { issuer: 'sp_entity_id' }
  static_options = saml_options.merge(path_prefix: path_prefix)

  config.omniauth :saml, static_options.merge(handler.provider_options)
```
